services:
  - type: web
    name: ggcfest
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        fromDatabase:
          name: ggcfest-db
          property: connectionString

databases:
  - name: ggcfest-db
    plan: basic_256mb
    region: singapore
